// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace UI.Models
{
    public partial class Software
    {
        public Software()
        {
            SoftwareDatabases = new ObservableCollection<SoftwareDataBase>();
        }
        [DisplayName("Код")]
        public int Id { get; set; }
        [DisplayName("Назва")]
        public string Name { get; set; }
        [Bindable(BindableSupport.No)]
        public int? IdUser { get; set; }
        [Display(AutoGenerateField = false)]
        public int IdOperatingSystem { get; set; }
        [DisplayName("Операційна система"),]
        public virtual OperatingSystem IdOperatingSystemNavigation { get; set; }
        public virtual User IdUserNavigation { get; set; }
        public virtual ObservableCollection<SoftwareDataBase> SoftwareDatabases { get; set; }
    }
}