// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;

namespace UI.Models
{
    public partial class DataBase
    {
        public DataBase()
        {
            SoftwareDatabases = new ObservableCollection<SoftwareDataBase>();
        }
        [DisplayName("Код")]
        public int Id { get; set; }
        [DisplayName("Название")]
        public string Name { get; set; }

        public int? IdServer { get; set; }

        [DisplayName("Сервер")]
        public virtual Server IdServerNavigation { get; set; }

        public virtual ObservableCollection<SoftwareDataBase> SoftwareDatabases { get; set; }
    }
}