// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;

namespace UI.Models
{
    public partial class OperatingSystem
    {
        public OperatingSystem()
        {
            Softwares = new ObservableCollection<Software>();
        }

        [DisplayName("Код")]
        public int Id { get; set; }
        [DisplayName("Назва")]
        public string Name { get; set; }
        [DisplayName("Розрядність")]
        public string Capacity { get; set; }
        public virtual ObservableCollection<Software> Softwares { get; set; }

        public override string ToString() { return $"{Name}"; }
    }
}