// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace UI.Models
{
    public partial class User
    {
        public User()
        {
            Softwares = new ObservableCollection<Software>();
        }
        [DisplayName("Код")]
        public int Id { get; set; }
        [DisplayName("Ім'я")]
        public string FirstName { get; set; }
        [DisplayName("Призвище")]
        public string MiddleName { get; set; }
        [DisplayName("Побатькові")]
        public string LastName { get; set; }
        [Display(Name = null)]
        public virtual ObservableCollection<Software> Softwares { get; set; }
    }
}